version: 3
endpoint: http://localhost:8080
metadata_directory: hasura/metadata
migrations_directory: hasura/migrations
admin_secret: admin_secret
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
