name: npm publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.9.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Login to npm using access token
        run: pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}

      - name: Build and publish to npm
        run: pnpm publish
